2024-12-24 00:33:05,746 - INFO - "test_run" выполнен успешно
2024-12-24 00:33:05,746 - ERROR - msg=e, exc_info=True)
Traceback (most recent call last):
  File "E:\mywork\myproject\py\lessons\simple_tasks\modules\module_12_4.py", line 86, in test_run_fault
    worker = runner.Runner(True, -10)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\mywork\myproject\py\lessons\simple_tasks\modules\HumanMoveTest\runner_and_tournament.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано bool
2024-12-24 00:33:05,747 - INFO - "test_walk" выполнен успешно
2024-12-24 00:33:05,747 - ERROR - Скорость не может быть отрицательной, сейчас -10
Traceback (most recent call last):
  File "E:\mywork\myproject\py\lessons\simple_tasks\modules\module_12_4.py", line 64, in test_walk_fault
    worker = runner.Runner('Vasya', -10)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\mywork\myproject\py\lessons\simple_tasks\modules\HumanMoveTest\runner_and_tournament.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -10
